// <auto-generated />
namespace Bangazon_MVC_InitialSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class model_update_foreignkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_update_foreignkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201705101959267_model_update_foreignkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
