// <auto-generated />
namespace Bangazon_MVC_InitialSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateproductmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateproductmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131648422_updateproductmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
